version: "3.7"

services:

  open-stock-market-api:
    image:  open-stock-market-api
    build: 
      context: .
    container_name: open-stock-market-api
    ports:
      - "80:5000"
    environment:
      -  PORT=5000
    depends_on:
      - "redis"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "56379:6379"
    networks:
      - osmapi-network

  open-stock-market-api-swagger:
    image: swaggerapi/swagger-ui:v3.19.4
    container_name: open-stock-market-api-swagger
    ports:
      - "5555:8080"
    environment:
      - API_URL=open-stock-market-api.yaml
    volumes:
      -  ./swagger/open-stock-market-api.yaml:/usr/share/nginx/html/open-stock-market-api.yaml

networks: 
    osmapi-network:
      driver: bridge